CREATE TABLE USER_MASTER(
    USER_ID INT AUTO_INCREMENT PRIMARY KEY,
    LOGIN_NAME  VARCHAR(100) UNIQUE,
    PASSWORD VARCHAR(100) NOT NULL,
    FIRST_NAME VARCHAR(100) NOT NULL,
    LAST_NAME VARCHAR(100) NOT NULL
) ;
